services:
  web:
    container_name: modulemanager-app-prod
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=0
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=django123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:16-alpine
    container_name: modulemanager-db-prod
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: django123
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d djangodb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
