services:
  db:
    image: postgres:16-alpine
    container_name: modulemanager-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: django123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d djangodb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: