# Generated by Django 6.0.5 on 2026-05-20 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='module',
            name='delivery_mode',
            field=models.CharField(choices=[('face-to-face', 'Face-to-face'), ('remote', 'Remote')], default='face-to-face', max_length=12),
        ),
        migrations.AddField(
            model_name='module',
            name='faculty',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('lithuanian', 'Lithuanian'), ('english', 'English')], default='lithuanian', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('compulsory', 'Compulsory'), ('optional', 'Optional')], default='compulsory', max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='teacher',
            field=models.CharField(max_length=60),
        ),
    ]
